const { createApp } = Vue;
createApp({
 data(){return{region:'구미',view:'home',map:null,markerLayer:null,places:window.GUMI_PLACES||[],selectedCategory:'전체',searchKeyword:'',placePopup:null,brokenImages:{},chatOpen:false,chatInput:'',chatMessages:[],editingPostId:null,currentPost:null,boardFilters:{category:'전체',place:'전체 장소',keyword:''},passwordModal:{open:false,action:'',value:'',error:'',show:false},postForm:{title:'',content:'',placeId:'',author:'',password:''},posts:[]}},
 computed:{
  mapCategories(){return ['관광지','음식점','축제공연행사','문화시설','레포츠','숙박','쇼핑','여행코스']},
  filteredPlaces(){const k=this.searchKeyword.toLowerCase();let arr=this.places.filter(p=>!k||`${p.name} ${p.address} ${p.category}`.toLowerCase().includes(k));if(this.selectedCategory==='게시글 많은 곳') return arr.filter(p=>this.postsForPlace(p.id).length>0).sort((a,b)=>this.postsForPlace(b.id).length-this.postsForPlace(a.id).length);if(this.selectedCategory!=='전체')arr=arr.filter(p=>p.category===this.selectedCategory);return arr},
  filteredPosts(){const k=this.boardFilters.keyword.toLowerCase();return this.posts.filter(post=>{const p=this.placeById(post.placeIds[0]);return (this.boardFilters.category==='전체'||p?.category===this.boardFilters.category)&&(this.boardFilters.place==='전체 장소'||p?.name===this.boardFilters.place)&&(!k||`${post.title} ${post.content}`.toLowerCase().includes(k))})}
 },
 mounted(){this.loadPosts();this.$nextTick(()=>this.initMap())},
 methods:{
  loadPosts(){const saved=localStorage.getItem('localhub-posts');if(saved){this.posts=JSON.parse(saved);return}const picks=[this.places.find(p=>p.category==='음식점'),this.places.find(p=>p.category==='축제공연행사'),this.places.find(p=>p.category==='관광지')].filter(Boolean);this.posts=[{id:'p1',title:'숨은 맛집 추천합니다!',content:'여기 정말 맛있어요! 현지인만 아는 곳입니다 ㅎㅎ',author:'익명',password:'1234',placeIds:[picks[0]?.id],createdAt:new Date(Date.now()-2*3600000).toISOString(),views:123,comments:[{id:'c1',author:'익명1',content:'맛있어 보여요!'},{id:'c2',author:'익명2',content:'위치가 어디인가요?'}]},{id:'p2',title:'이번 주 축제 후기',content:'사람도 많고 볼거리도 다양했습니다.',author:'구미주민',password:'1234',placeIds:[picks[1]?.id],createdAt:new Date(Date.now()-5*3600000).toISOString(),views:98,comments:[{id:'c3',author:'익명',content:'주차는 어떤가요?'}]},{id:'p3',title:'구미 여행 코스 공유해요',content:'오전에 산책하고 오후에는 근처 문화시설을 둘러보는 코스입니다.',author:'여행자',password:'1234',placeIds:[picks[2]?.id],createdAt:new Date(Date.now()-86400000).toISOString(),views:156,comments:[]}];this.savePosts()},
  savePosts(){localStorage.setItem('localhub-posts',JSON.stringify(this.posts))},
  initMap(){if(!window.L)return;this.map=L.map('map',{center:[36.1195,128.3446],zoom:12,preferCanvas:true});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(this.map);this.markerLayer=L.layerGroup().addTo(this.map);this.renderMarkers();setTimeout(()=>this.map.invalidateSize(),100)},
  renderMarkers(){if(!this.markerLayer)return;this.markerLayer.clearLayers();this.filteredPlaces.forEach(place=>{const marker=L.marker([place.latitude,place.longitude],{icon:L.divIcon({className:'marker-wrap',html:`<div class="marker marker-${place.contentTypeId}">${place.categoryIcon}</div>`,iconSize:[36,44],iconAnchor:[18,44]})});marker.on('click',()=>this.placePopup=place);marker.bindTooltip(place.name,{direction:'top',offset:[0,-35]});marker.addTo(this.markerLayer)})},
  selectCategory(c){this.selectedCategory=c;this.$nextTick(()=>{this.renderMarkers();this.fitMarkers()})},
  applySearch(){this.view='home';this.$nextTick(()=>{this.renderMarkers();this.fitMarkers()})},
  fitMarkers(){if(!this.map||!this.filteredPlaces.length)return;const b=L.latLngBounds(this.filteredPlaces.map(p=>[p.latitude,p.longitude]));this.map.fitBounds(b,{padding:[35,35],maxZoom:14})},
  goHome(){this.view='home';this.$nextTick(()=>{this.map?.invalidateSize();this.renderMarkers()})},
  openPost(post){post.views++;this.currentPost=post;this.savePosts();this.view='detail'},
  openPlacePosts(place){this.placePopup=null;this.boardFilters.place=place.name;this.view='list'},
  postsForPlace(id){return this.posts.filter(p=>p.placeIds.includes(id))},placeById(id){return this.places.find(p=>p.id===id)},placeName(id){return this.placeById(id)?.name||'장소 미지정'},
  focusPlaceById(id){const p=this.placeById(id);if(!p)return;this.placePopup=p;this.view='home';this.$nextTick(()=>{this.map?.invalidateSize();this.map?.flyTo([p.latitude,p.longitude],15)})},
  startWrite(){this.editingPostId=null;this.postForm={title:'',content:'',placeId:'',author:'',password:''};this.view='write'},
  submitPost(){if(this.editingPostId){const i=this.posts.findIndex(p=>p.id===this.editingPostId);this.posts[i]={...this.posts[i],title:this.postForm.title,content:this.postForm.content,author:this.postForm.author,password:this.postForm.password,placeIds:[this.postForm.placeId]};this.currentPost=this.posts[i]}else{this.posts.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:this.postForm.title,content:this.postForm.content,author:this.postForm.author,password:this.postForm.password,placeIds:[this.postForm.placeId],createdAt:new Date().toISOString(),views:0,comments:[]});this.currentPost=this.posts[0]}this.savePosts();this.view='detail'},
  requestPassword(action){this.passwordModal={open:true,action,value:'',error:'',show:false}},
  confirmPassword(){if(this.passwordModal.value!==this.currentPost.password){this.passwordModal.error='비밀번호가 일치하지 않습니다.';return}const action=this.passwordModal.action;this.passwordModal.open=false;if(action==='delete'){this.posts=this.posts.filter(p=>p.id!==this.currentPost.id);this.savePosts();this.currentPost=null;this.view='list'}else{this.editingPostId=this.currentPost.id;this.postForm={title:this.currentPost.title,content:this.currentPost.content,placeId:this.currentPost.placeIds[0],author:this.currentPost.author,password:this.currentPost.password};this.view='write'}},
  togglePasswordVisibility(e){const input=e.target.closest('.password-modal').querySelector('input[type="password"], input[type="text"]');if(input)input.type=this.passwordModal.show?'text':'password'},
  markBroken(id){this.brokenImages={...this.brokenImages,[id]:true}},placeReviews(id){return JSON.parse(localStorage.getItem('gumi-community-reviews')||'{}')[id]||[]},placeRating(id){const r=this.placeReviews(id);return r.length?(r.reduce((s,x)=>s+Number(x.rating),0)/r.length).toFixed(1):'0.0'},
  categoryIcon(c){return({전체:'🗺️',관광지:'📍',음식점:'🍽️',축제공연행사:'🎉',문화시설:'🎨',레포츠:'🏃',숙박:'🏨',쇼핑:'🛍️',여행코스:'🧭'})[c]||'📌'},
  formatDate(d){return new Date(d).toLocaleString('ko-KR')},relativeDate(d){const diff=Date.now()-new Date(d);if(diff<3600000)return `${Math.max(1,Math.floor(diff/60000))}분 전`;if(diff<86400000)return `${Math.floor(diff/3600000)}시간 전`;return `${Math.floor(diff/86400000)}일 전`},
  sendChat(){if(!this.chatInput)return;const q=this.chatInput;this.chatMessages.push({role:'user',text:q});const k=q.replace(/추천|해줘|알려줘|구미|장소|지역/g,'').trim();const matches=this.places.filter(p=>`${p.name} ${p.category} ${p.address}`.includes(k||'음식점')).slice(0,3);this.chatMessages.push({role:'bot',text:matches.length?`추천 장소: ${matches.map(p=>p.name).join(', ')}`:'조건에 맞는 장소를 찾지 못했어요. 관광지, 음식점, 축제처럼 입력해보세요.'});this.chatInput=''}
 },watch:{searchKeyword(){clearTimeout(this.t);this.t=setTimeout(()=>this.renderMarkers(),150)},view(v){if(v==='home')this.$nextTick(()=>setTimeout(()=>this.map?.invalidateSize(),50))}}
}).mount('#app');